name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
  build:
    name: Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        env:
          BUILD_HOOK_URL: ${{ secrets.BUILD_HOOK_URL }}
        run: curl -X POST -d {} $BUILD_HOOK_URL
